/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSantriRouteImport } from './routes/_app.santri'
import { Route as AppRekapRouteImport } from './routes/_app.rekap'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppInputRouteImport } from './routes/_app.input'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSantriRoute = AppSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AppRoute,
} as any)
const AppRekapRoute = AppRekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppInputRoute = AppInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/input': typeof AppInputRoute
  '/ranking': typeof AppRankingRoute
  '/rekap': typeof AppRekapRoute
  '/santri': typeof AppSantriRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/input': typeof AppInputRoute
  '/ranking': typeof AppRankingRoute
  '/rekap': typeof AppRekapRoute
  '/santri': typeof AppSantriRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/input': typeof AppInputRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/rekap': typeof AppRekapRoute
  '/_app/santri': typeof AppSantriRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/input' | '/ranking' | '/rekap' | '/santri'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/input' | '/ranking' | '/rekap' | '/santri' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/input'
    | '/_app/ranking'
    | '/_app/rekap'
    | '/_app/santri'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/santri': {
      id: '/_app/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof AppSantriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rekap': {
      id: '/_app/rekap'
      path: '/rekap'
      fullPath: '/rekap'
      preLoaderRoute: typeof AppRekapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/input': {
      id: '/_app/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof AppInputRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInputRoute: typeof AppInputRoute
  AppRankingRoute: typeof AppRankingRoute
  AppRekapRoute: typeof AppRekapRoute
  AppSantriRoute: typeof AppSantriRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInputRoute: AppInputRoute,
  AppRankingRoute: AppRankingRoute,
  AppRekapRoute: AppRekapRoute,
  AppSantriRoute: AppSantriRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
